repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=79]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=79, --ignore=E501 W503]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.16.0"
    hooks:
      - id: pylint
        args: ["-sn", "--rcfile=pyproject.toml", --disable=W0511]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        args: ["-v"]
        additional_dependencies: [requests==2.28.2]
default_language_version:
  python: python3.11.1
