version: "3.11"

services:
  github_api:
    image: github_api_service:0.1
    build:
      context: ./app
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./app:/app
volumes:
  data:
